logdir: ../../../logs/cgan/mnist/debug
test_epoch: 50

train_data_params:
  labels:
    - 0
  with_label: False

test_data_params:
  phase: test
  with_label: False

generator_params:
  latent_dim: 100
  nb_filter: 32
  last_activation: tanh
  normalization: batch
  upsampling: deconv

discriminator_params:
  nb_filter: 32
  normalization: batch
  downsampling: stride

solver_params:
  lr_g: 0.0001
  lr_d: 0.001
  density_threshold: 0.005

fit_params:
  nb_epoch: 100
  visualize_steps: 1
  save_steps: 1
